/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      franka_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

      franka_hand_controller:
        type: position_controllers/GripperActionController

  franka_robot_state_broadcaster:
    ros__parameters:
      arm_id: franka

  franka_arm_controller:
    ros__parameters:
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      joints:
        - franka_joint1
        - franka_joint2
        - franka_joint3
        - franka_joint4
        - franka_joint5
        - franka_joint6
        - franka_joint7
      # gains:
      #   franka_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      #   franka_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      #   franka_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      #   franka_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      #   franka_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      #   franka_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      #   franka_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

  franka_hand_controller:
    ros__parameters:
      joint: franka_finger_joint1

